---
apiVersion: v1
kind: Secret
metadata:
  name: freebox-credentials
  namespace: system
type: Opaque
stringData:
  app_id: ${FREEBOX_APP_ID}
  token: ${FREEBOX_TOKEN}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: freebox-config
  namespace: system
data:
  endpoint: ${FREEBOX_ENDPOINT}
  version: ${FREEBOX_VERSION}
