---
apiVersion: v1
kind: Secret
metadata:
  name: freebox-secret
  namespace: system
type: Opaque
stringData:
  token: ${FREEBOX_TOKEN}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: freebox-config
  namespace: system
data:
  endpoint: ${FREEBOX_ENDPOINT}
  version: ${FREEBOX_VERSION}
  app_id: ${FREEBOX_APP_ID}
  device: ${FREEBOX_DEVICE}
