apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: FreeboxMachineTemplate
metadata:
  name: freeboxmachinetemplate-sample
  namespace: default
spec:
  template:
    spec:
      name: sample-vm
      vcpus: 2
      memoryMB: 4096
      diskSizeBytes: 21474836480 # 20GB
      imageURL: https://factory.talos.dev/image/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba/v1.11.5/nocloud-arm64.raw.xz
