apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: FreeboxCluster
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-freebox
    app.kubernetes.io/managed-by: kustomize
  name: freeboxcluster-sample
spec:
  controlPlaneEndpoint:
    host: "192.168.1.100"
    port: 6443
