apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster-api-provider-freebox-system

namePrefix: cluster-api-provider-freebox-

commonLabels:
  app.kubernetes.io/name: cluster-api-provider-freebox
  app.kubernetes.io/managed-by: kustomize

bases:
- ../default

patchesStrategicMerge:
- freebox-env-patch.yaml

images:
- name: controller
  newName: example.com/cluster-api-provider-freebox
  newTag: e2e
