# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/infrastructure.cluster.x-k8s.io_freeboxclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_freeboxmachines.yaml
- bases/infrastructure.cluster.x-k8s.io_freeboxmachinetemplates.yaml
# +kubebuilder:scaffold:crdkustomizeresource

labels:
- pairs:
    cluster.x-k8s.io/v1beta1: v1alpha1
    cluster.x-k8s.io/v1beta2: v1alpha1
  includeSelectors: true

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
